### ISSUE TITLE
Asking about Covid dataset

### ISSUE THREAD

**Issue by yobrepus** [mahfuzmohammad/HealthyGAN#1]
I follow the link about dataset that you provide. It seem they use data from Kaggle (https://www.kaggle.com/datasets/andyczhao/covidx-cxr2?select=competition_test). However, when I download and extract to the path based on your instruction. I found that the data from Kaggle are not fit with your pickle file. Would you please suggest me how to generate the covid dataset that you use.

**Comment by mahfuzmohammad** [comment]
Did you try https://github.com/lindawangg/COVID-Net/blob/master/docs/COVIDx.md#steps-to-generate-the-dataset

**Comment by nnajeh** [comment]
I would like to know the number of epochs to reach the convergence, and how long it takes to run the model. Thank you.

**Comment by mahfuzmohammad** [comment]
I think 400K is good enough but definitely you can try more. With 256x256
image size and batch size 8, 400K takes around 15 hrs on A100 gpu.
