### ISSUE TITLE
Learning and utilizing datasets from other tasks

### ISSUE THREAD

**Issue by Junhyuk93** [mahfuzmohammad/HealthyGAN#2]
Hello,

I would like to apply your architecture to other medical domain tasks. (ex : CT, MRI ... )
Have you ever tried this and, if so, was the result good?

I look forward to your reply, thank you. :)

**Comment by mahfuzmohammad** [comment]
Thank you for your interest. The migraine detection task in the paper used
MRI data.

**Comment by Junhyuk93** [comment]
I want to use CT data of 2D slices. I'm trying to fit the dataset structure, but I'm having trouble with the pickle file.
How do I make a pickle file?
