### ISSUE TITLE
Asking about code

### ISSUE THREAD

**Issue by zakiindra** [mahfuzmohammad/HealthyGAN#4]
I am trying to reproduce the project and having difficulties understanding the code. Let this issue be the thread where I am asking anything about the project.

First question.
I see this code to produce outputs of Discriminator model:
```
    def forward(self, x):
        h = self.main(x)
        out_src = self.conv1(h)
        return h, out_src
```

I see that `out_src` is used in training, but I am not finding `h` used anywhere. What is `h` here? And how is it used in the project?

Thank you.

**Comment by mahfuzmohammad** [comment]
I appreciate your interest. The h is not being used in the project. I left it here for debugging purposes.

**Comment by zakiindra** [comment]
Thank you for responding to my questions. I have another question.

What is the purpose of `crop_top` and `central_crop`? Is there any specific reason of why the percentage of `crop_top' was set to 0.15?

**Comment by mahfuzmohammad** [comment]
These are some utility functions to remove white spaces from the images. These are dataset-specific.
