### ISSUE TITLE
difficulty in undertsanding the paper

### ISSUE THREAD

**Issue by ytz123456** [mahfuzmohammad/HealthyGAN#5]
Hi @mahfuzmohammad:
Thank you for sharing the fantastic work! I am an undergraduate student studying utilizing GAN for anomaly detection. While reading your paper, I find it difficult to follow the idea of using **attention masks**. Would you mind sharing some literature to help me understand this idea? Thank you so much!

**Comment by mahfuzmohammad** [comment]
Hi. I appreciate your interest. You may check out this nice survey paper https://arxiv.org/pdf/2204.07756.pdf

The mask in HealthyGAN is, however, much simpler.

I hope it helps.
